/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    finddevice
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JNI_finddevice
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     JNI
 * Method:    packet
 * Signature: ([I[Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_JNI_packet
  (JNIEnv *, jclass, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
